### ISSUE TITLE
User can see the list of courses with performance summary and overall performance (GPA, Letter Grade) for the semester

### ISSUE THREAD

**Issue by max172-hqt** [max172-hqt/grade-tracker#3]
As a user, I can **see the list of courses with performance summary and overall performance for the semester**

**Comment by jeffverz** [comment]
- [x] list down all courses
- [x] compute and display the over-all performance

**Comment by jeffverz** [comment]
The issue couldn't be completed due personal scheduling as well as the technical preparation for the requirement.

**Comment by jeffverz** [comment]
Issue completed
